# Generated by Django 2.0.7 on 2018-08-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.TextField(max_length=2000)),
                ('gene_type', models.CharField(max_length=100)),
                ('gene_family', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdgeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='querytgdb.Annotation')),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfs', to='querytgdb.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Analysis')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Edge')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldchange', models.FloatField()),
                ('p_value', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Analysis')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Annotation')),
            ],
        ),
        migrations.AddField(
            model_name='edgedata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.EdgeType'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Experiment'),
        ),
        migrations.AlterUniqueTogether(
            name='regulation',
            unique_together={('analysis', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('analysis', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='experimentdata',
            unique_together={('experiment', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='edgedata',
            unique_together={('tf', 'target', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='analysisdata',
            unique_together={('analysis', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('experiment', 'name')},
        ),
    ]
