# Generated by Django 2.0.7 on 2018-08-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='querytgdb.Annotation')),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfs', to='querytgdb.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='edgedata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.EdgeType'),
        ),
    ]
