# Generated by Django 2.1.2 on 2018-10-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0002_auto_20180804_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='edge',
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.MetaKey'),
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querytgdb.MetaKey'),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
    ]
