# Generated by Django 2.0.7 on 2018-08-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0002_auto_20180801_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edgedata',
            unique_together={('tf', 'target', 'type')},
        ),
    ]
