# Generated by Django 2.1.2 on 2018-10-16 14:30

from django.db import migrations
import querytgdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0003_auto_20181015_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='foldchange',
            field=querytgdb.models.NumpyFloat(null=True),
        ),
    ]
