# Generated by Django 2.1.2 on 2018-10-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0004_auto_20181016_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='tf',
        ),
        migrations.AlterUniqueTogether(
            name='experimentdata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='experimentdata',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experimentdata',
            name='key',
        ),
        migrations.AddField(
            model_name='analysis',
            name='tf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='querytgdb.Annotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ExperimentData',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
    ]
