# Generated by Django 2.1.2 on 2018-10-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0005_auto_20181018_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='name',
        ),
    ]
