# Generated by Django 5.0 on 2024-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytgdb', '0007_auto_20190117_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FilePathField()),
                ('type', models.CharField(max_length=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
