# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField()),
                ('text', models.CharField(db_column='edge_name', max_length=100)),
            ],
            options={
                'verbose_name': 'Edges',
                'verbose_name_plural': 'Edgess',
                'db_table': 'Edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.IntegerField()),
                ('node_1_id', models.IntegerField()),
                ('node_2_id', models.IntegerField()),
                ('edge_id', models.IntegerField()),
                ('meta_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Interactions',
                'verbose_name_plural': 'Interactionss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('meta_p', models.IntegerField()),
                ('meta_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='meta_value', max_length=100)),
                ('meta_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'Meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('text', models.CharField(db_column='node_name', max_length=100)),
                ('node_type', models.CharField(db_column='node_type', max_length=100)),
            ],
            options={
                'verbose_name': 'Nodes',
                'verbose_name_plural': 'Nodess',
                'db_table': 'Nodes',
                'managed': False,
            },
        ),
    ]
