# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edges',
            options={'managed': False, 'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
        migrations.AlterModelOptions(
            name='interactions',
            options={'managed': False, 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='nodes',
            options={'managed': False, 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelTable(
            name='interactions',
            table='Interactions',
        ),
    ]
